### ISSUE TITLE
Getting error while trying to retrieve cost for using Custom timeframe

### ISSUE THREAD

**Issue by ajmal-yazdani** [mivano/azure-cost-cli#10]
I am trying to get Azure cost for last month and trying to use Custom timeframe using "from" and "to" date, but getting error,

`Error: Object reference not set to an instance of an object.`

Here is the stack:

❯ azure-cost show -s XXXXXXXXXXXXXXXXXXXXXXX --timeframe Custom --from 3/1/2023 --to 3/31/2023 --debug
Using token credential: ChainedTokenCredential to fetch a token.
Token retrieved and expires at: 4/16/2023 8:33:02 AM +00:00
Retrieving costs from /subscriptions/XXXXXXXXXXXXXXXXXXXXXXX/providers/Microsoft.CostManagement/query?api-version=2021-10-01&$top=5000 using
the following payload:
{
   "type": "ActualCost",
   "timeframe": "Custom",
   "timePeriod": {
      "from": "2023-03-01",
      "to": "2023-03-31"
   },
   "dataSet": {
      "granularity": "Daily",
      "aggregation": {
         "totalCost": {
            "name": "Cost",
            "function": "Sum"
         },
         "totalCostUSD": {
            "name": "CostUSD",
            "function": "Sum"
         }
      },
      "sorting": [
         {
            "direction": "Ascending",
            "name": "UsageDate"
         }
      ]
   }
}
Response status code is OK and got payload size of
Retrieving costs from /subscriptions/XXXXXXXXXXXXXXXXXXXXXXX/providers/Microsoft.CostManagement/forecast?api-version=2021-10-01&$top=5000 using
the following payload:
{
   "type": "ActualCost",
   "dataSet": {
      "granularity": "Daily",
      "aggregation": {
         "totalCost": {
            "name": "Cost",
            "function": "Sum"
         }
      },
      "sorting": [
         {
            "direction": "Ascending",
            "name": "UsageDate"
         }
      ],
      "filter": {
         "Dimensions": {
            "Name": "PublisherType",
            "Operator": "In",
            "Values": [
               "azure"
            ]
         }
      }
   }
}
Response status code is OK and got payload size of
Retrieving costs from /subscriptions/XXXXXXXXXXXXXXXXXXXXXXX/providers/Microsoft.CostManagement/query?api-version=2021-10-01&$top=5000 using
the following payload:
{
   "type": "ActualCost",
   "timeframe": "Custom",
   "timePeriod": {
      "from": "2023-03-01",
      "to": "2023-03-31"
   },
   "dataSet": {
      "granularity": "None",
      "aggregation": {
         "totalCost": {
            "name": "Cost",
            "function": "Sum"
         },
         "totalCostUSD": {
            "name": "CostUSD",
            "function": "Sum"
         }
      },
      "sorting": [
         {
            "direction": "Ascending",
            "name": "UsageDate"
         }
      ],
      "grouping": [
         {
            "type": "Dimension",
            "name": "ServiceName"
         }
      ],
      "filter": {
         "Dimensions": {
            "Name": "PublisherType",
            "Operator": "In",
            "Values": [
               "azure"
            ]
         }
      }
   }
}
Response status code is OK and got payload size of
Retrieving costs from /subscriptions/XXXXXXXXXXXXXXXXXXXXXXX/providers/Microsoft.CostManagement/query?api-version=2021-10-01&$top=5000 using
the following payload:
{
   "type": "ActualCost",
   "timeframe": "Custom",
   "timePeriod": {
      "from": "2023-03-01",
      "to": "2023-03-31"
   },
   "dataSet": {
      "granularity": "None",
      "aggregation": {
         "totalCost": {
            "name": "Cost",
            "function": "Sum"
         },
         "totalCostUSD": {
            "name": "CostUSD",
            "function": "Sum"
         }
      },
      "sorting": [
         {
            "direction": "Ascending",
            "name": "UsageDate"
         }
      ],
      "grouping": [
         {
            "type": "Dimension",
            "name": "ResourceLocation"
         }
      ],
      "filter": {
         "Dimensions": {
            "Name": "PublisherType",
            "Operator": "In",
            "Values": [
               "azure"
            ]
         }
      }
   }
}
Response status code is OK and got payload size of
Error: Object reference not set to an instance of an object.

**Comment by mivano** [comment]
Thanks for reporting, I think it is fixed in v0.8.0, released any minute now.
