### ISSUE TITLE
Exclude when filtering

### ISSUE THREAD

**Issue by Nastaliss** [mivano/azure-cost-cli#107]
Filters only seem to be [ inclusive  ](https://github.com/mivano/azure-cost-cli/blob/faa4a6bfd787051b2cc56abcedd4f56af1e78024/src/CostApi/AzureCostApiRetriever.cs#L88).
I was trying to exclude a certain tag but it looks like there is currently no way to do this.
I feel like this could be useful, what do you think ?

**Comment by mivano** [comment]
I agree this would be useful, but I wonder how to implement it. The [doc](https://learn.microsoft.com/en-us/rest/api/cost-management/query/usage?view=rest-cost-management-2023-11-01&tabs=HTTP#queryoperatortype) does not specify a `NotIn` operator. You might be able to combine this with a jsonpath query to filter out the tag? But it will fetch it first from the API and will do the additional filtering after retrieving the data.

**Comment by mivano** [comment]
Closing this for now. I like the suggestion, but I do not see an easy way to implement this. Feel free to reopen if you have an idea.
