### ISSUE TITLE
timeframe TheLastMonth error

### ISSUE THREAD

**Issue by AndTraHTI** [mivano/azure-cost-cli#119]
I am using the following comand to extract my monthly cost:
azure-cost dailyCosts -b xxxxxxx --timeframe TheLastMonth --dimension ResourceGroupName --includeTags -o json

The timeframe TheLastMonth generates the following error:
Error: Response status code does not indicate success: 400 (Bad Request).

If I use TheLastBillingMonth as a timeframe the comand works just fine. 

Is anybody facing a similar issue?

**Comment by mivano** [comment]
Can you include the --debug flag and include the output in this issue? Might gives an idea why it throws a bad request.

**Comment by AndTraHTI** [comment]
**This is the error if I specigy the Enterprise Agreement**
azure-cost dailyCosts -b xxxxxx --timeframe TheLastMonth --dimension ResourceGroupName --includeTags -o json --debug
Version: 0.37.0.0
No subscription ID specified. Trying to retrieve the default subscription ID from Azure CLI.
Default subscription ID retrieved from az cli: xxxxx-xxxxx-xxxxx-xxxxx-xxxxx
Using token credential: ChainedTokenCredential to fetch a token.
Token retrieved and expires at: 3/14/2024 9:16:23 AM +00:00
Retrieving data from /providers/Microsoft.Billing/billingAccounts/xxxxxx/providers/Microsoft.CostManagement/query?api-version=2023-03-01&$top=5000 using the following payload:
{                            
   "type": "ActualCost",
   "timeframe": "TheLastMonth",
   "timePeriod": null,
   "dataSet": {
      "granularity": "Daily",
      "include": [
         "Tags"
      ],
      "aggregation": {
         "totalCost": {
            "name": "Cost",
            "function": "Sum"
         },
         "totalCostUSD": {
            "name": "CostUSD",
            "function": "Sum"
         }
      },
      "sorting": [
         {
            "direction": "Ascending",
            "name": "UsageDate"
         }
      ],
      "grouping": [
         {
            "type": "Dimension",
            "name": "ResourceGroupName"
         },
         {
            "type": "Dimension",
            "name": "ChargeType"
         }
      ],
      "filter": null
   }
                              
Response status code is BadRequest and got payload size of 171
Response content: {"error":{"code":"BadRequest","message":"Invalid query definition, timeframe TheLastMonth is currently not supported. (Request ID: 3f15c49e-8aab-454a-84b5-c6f1d48fc45b)"}}**


**This is the error if I specigy a Subscription**
azure-cost dailyCosts -s xxxxx-xxxxx-xxxxx-xxxxx-xxxxx --timeframe TheLastMonth --dimension ResourceGroupName --includeTags -o json --debug
Version: 0.37.0.0
Using token credential: ChainedTokenCredential to fetch a token.
Token retrieved and expires at: 3/14/2024 9:16:23 AM +00:00
Retrieving data from /subscriptions/xxxxx-xxxxx-xxxxx-xxxxx-xxxxx/providers/Microsoft.CostManagement/query?api-version=2023-03-01&$top=5000 using the following payload:
{                            
   "type": "ActualCost",
   "timeframe": "TheLastMonth",
   "timePeriod": null,
   "dataSet": {
      "granularity": "Daily",
      "include": [
         "Tags"
      ],
      "aggregation": {
         "totalCost": {
            "name": "Cost",
            "function": "Sum"
         },
         "totalCostUSD": {
            "name": "CostUSD",
            "function": "Sum"
         }
      },
      "sorting": [
         {
            "direction": "Ascending",
            "name": "UsageDate"
         }
      ],
      "grouping": [
         {
            "type": "Dimension",
            "name": "ResourceGroupName"
         },
         {
            "type": "Dimension",
            "name": "ChargeType"
         }
      ],
      "filter": null
   }
}                             
Response status code is BadRequest and got payload size of 171
Response content: {"error":{"code":"BadRequest","message":"Invalid query definition, timeframe TheLastMonth is currently not supported. (Request ID: e448266d-d705-48a8-b047-3fb2d75057db)"}}
Error: Response status code does not indicate success: 400 (Bad Request).

**Comment by mivano** [comment]
Looks like you cannot use the LastMonth as an option here: `timeframe TheLastMonth is currently not supported. `
Not sure why, the API documentation is not that great. Try to specify a custom date range otherwise?

**Comment by AndTraHTI** [comment]
We will just use TheLastBillingMonth instead. Thanks!
