### ISSUE TITLE
Error when running the command azure-cost dailyCosts -b locally

### ISSUE THREAD

**Issue by AndTraHTI** [mivano/azure-cost-cli#120]
hi @mivano, after authenticating on my local Azure CLI with az login --tenant or az login, I am trying to run the following comand:

_azure-cost dailyCosts -b xxxxxxx --timeframe BillingMonthToDate --dimension ResourceGroupName --includeTags -o json_

Unfortunatly, I get the following error:
_System.ArgumentException: Missing subscription ID. Please specify a subscription ID or login to Azure CLI.
   System.ComponentModel.Win32Exception: An error occurred trying to start process 'az' with working directory
   'C:\Users\xxxxxx'. The system cannot find the file specified.
     at bool System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
     at string AzureCostCli.Infrastructure.AzCommand.GetDefaultAzureSubscriptionId() in
        /home/runner/work/azure-cost-cli/azure-cost-cli/src/Infrastructure/AzCommand.cs:22
     at async Task<int> AzureCostCli.Commands.DailyCost.DailyCostCommand.ExecuteAsync(CommandContext context,
        DailyCostSettings settings) in /home/runner/work/azure-cost-cli/azure-cost-cli/src/Commands/DailyCost/
        DailyCost.cs:73_

It works if I run the same comand on the Azure Cloud shell. It also work if I specify a certain subscription with the -s switch. It would be really cool to get a report of all my subscriptions.

**Comment by mivano** [comment]
Looks like there are some cases where the subscription id is not needed, but is still being retrieved. Thanks for reporting, I will change it in the next version.
