### ISSUE TITLE
incorrect value for accumulatedCost report Last 30 days:

### ISSUE THREAD

**Issue by joekru** [mivano/azure-cost-cli#129]
It appears that the value of "Since start of <month>" is also being used for "Last 30 days".  The information does not match the actual from Azure portal.  Actual Last 30 days is much higher than the command line output shows.

azure-cost accumulatedCost -s <subid>
                                                                                Azure Cost Overview for <subname> from 4/1/2024 to 4/9/2024
┌─                                                                  Azure Costs                                                                   ─┐                        Accumulated cost in USD
│  Today:                                                                      11.28 USD                                                           │  01 Apr  59.2
│  Yesterday:                                                                  59.43 USD                                                           │  02 Apr  126.91
│  Since start of Apr:                                                        **426.33 USD**                                                           │  03 Apr  187.62
│  Last 7 days:                                                               367.14 USD                                                           │  04 Apr  252.26
│  Last 30 days:                                                              **426.33 USD**

**Comment by mivano** [comment]
Thanks for reporting, I will have a look.
