### ISSUE TITLE
getting 400 error

### ISSUE THREAD

**Issue by mbenachour** [mivano/azure-cost-cli#146]
this was working couple days ago, but starting this morning I'm getting this error :
azure-cost detectAnomalies -o csv
Error: Response status code does not indicate success: 400 (Bad Request).

**Comment by mbenachour** [comment]
my bad, this is a permission issue on my end, will close the issue.

**Comment by mivano** [comment]
The API is not always that descriptive with its error codes. You can include the `-debug` option to see the underlying issue, but I m glad you found out already.
