### ISSUE TITLE
The grain Hourly not works

### ISSUE THREAD

**Issue by cunhaengineer** [mivano/azure-cost-cli#148]
How can i see the cost granularity in hours? I tried --grain "Hourly" but just group by daily

**Comment by DanielSpindler83** [comment]
Sorry, I cannot find any reference to --grain in the azure-cost-cli documentation or the code. (I could be missing something).
Did you see it in the doco?

My advice for hourly data is to use PowerBI, connect it to Azure Cost Management and you get hour by hour full data set.
Disadvantage is that you need to know how to wield PowerBI and the data set is very raw and verbose.

Pretty sure you can do all this for free using the local PowerBI Desktop App. You just can't publish or share it without licencing.
[https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management)

**Comment by mivano** [comment]
There is no granularity in hours supported by the [Azure endpoint](https://learn.microsoft.com/en-us/rest/api/cost-management/query/usage?view=rest-cost-management-2023-11-01&tabs=HTTP#granularitytype). 

It is also not possible in the portal
<img width="262" alt="image" src="https://github.com/mivano/azure-cost-cli/assets/668535/fa93970e-642d-4648-90db-74e628be168b">

So I m afraid it is not possible.
