### ISSUE TITLE
Piping the output to a file hides actual errors

### ISSUE THREAD

**Issue by MvRoo** [mivano/azure-cost-cli#150]
I use the tool to export costs to a csv or json file. The way that is supported by the tool is by piping it to a file output. This works fine most of the time. The challenge is when the tool returns an error. In this scenario the error output will also be written to the output file. I can imagine this was a conscious decision and that this is what you would want for some scenarios.

In my case I think it would help if we're able to influence what it does in that case. Perhaps write errors to the error output stream by default or be able to provide an argument that tells the tool what to do.

**Comment by mivano** [comment]
If there is an error, it should not just continue and write it to the same file. It should be clear to the caller that it has failed so it can recover. 

So yes, the error output makes more sense, but this is not correctly implemented at the moment. I will have a look at that. 

Thanks for the suggestion!

**Comment by mivano** [comment]
See #151. I think this will help. Let me know your thoughts.
