### ISSUE TITLE
Bug - Missing subscription ID. Please specify a subscription ID or login to Azure CLI

### ISSUE THREAD

**Issue by chaoscreater** [mivano/azure-cost-cli#155]
Hi, I think I have a similar issue to this:
https://github.com/mivano/azure-cost-cli/issues/120

The command I'm trying to run is this:
`azure-cost detectAnomalies --dimension ResourceId --recent-activity-days 4`

or simply this:
`azure-cost`

Here's the error:

```
System.ArgumentException: Missing subscription ID. Please specify a subscription ID or login to Azure CLI.
   System.ComponentModel.Win32Exception: An error occurred trying to start process 'az' with working directory 'D:\'. The system cannot find the file specified.
     at bool System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
     at string AzureCostCli.Infrastructure.AzCommand.GetDefaultAzureSubscriptionId() in /home/runner/work/azure-cost-cli/azure-cost-cli/src/Infrastructure/AzCommand.cs:22
     at async Task<int> AzureCostCli.Commands.DetectAnomaly.DetectAnomalyCommand.ExecuteAsync(CommandContext context, DetectAnomalySettings settings) in
        /home/runner/work/azure-cost-cli/azure-cost-cli/src/Commands/DetectAnomaly/DetectAnomaly.cs:72
```

I'm already logged in with AZ CLI. And if I do this, it sort of works:
`azure-cost detectAnomalies --dimension ResourceId --recent-activity-days 4 -s xxxxxxxxx-xxxxx-44e9-ae35-dc5694aabfa7`

But the output I get is just "Detected Anomalies" and nothing out is shown. If I run just this:

`azure-cost -s xxxxxxxxx-xxxxx-44e9-ae35-dc5694aabfa7`

Then I get some basic data shown.

I'm running this in Powershell 7.4.0 and I literally just installed azure-cost today.

Also, I have the latest AZ CLI x64 installed and I'm running Windows 11 build 22631 if it helps.

**Comment by mivano** [comment]
Thanks for the detailed report. I will have a look at this.
