### ISSUE TITLE
cost by service name and location are not displayed , any thoughts?

### ISSUE THREAD

**Issue by edco29** [mivano/azure-cost-cli#16]
![Screenshot 2023-04-17 at 23 02 11](https://user-images.githubusercontent.com/40572443/232668112-93b10e31-4b30-4cd5-852b-f68fb6fa106c.png)
# Subscription details:

> {
  "authorizationSource": "RoleBased",
  "displayName": "Azure for Students",
  "id": "/subscriptions/XXXXXXXXXXXX",
  "state": "Enabled",
  "subscriptionId": "XXXXXXXXXXXXX",
  "subscriptionPolicies": {
    "locationPlacementId": "Public_2014-09-01",
    "quotaId": "AzureForStudents_2018-01-01",
    "spendingLimit": "On"
  }
}

**Comment by mivano** [comment]
If you look at the list here: https://learn.microsoft.com/en-us/azure/cost-management-billing/costs/understand-cost-mgt-data#supported-microsoft-azure-offers and search for your offer `AzureForStudents_2018-01-01` then you will find it on the list of not (yet) supported offers. So cost management might not work correctly. Unfortunately not something to be fixed, unless there is another supported API that I can use.

**Comment by Ravian18** [comment]
@mivano The By service name and By location fields also stay empty for one of my subscriptions that has `quotaId` = `EnterpriseAgreement_2014-09-01` which is part of the supported offer lists.

**Comment by mivano** [comment]
@edco29 I see I did not respond yet to your last question; when using a `--query` with jmespath expression you can do some basic filtering, but I do not have anything yet to pass in filters to the actual query. Planning to do in #20.

**Comment by mivano** [comment]
Closing this issue for now. @edco29 the filtering on resource group is implemented, see the readme for details.

**Comment by edco29** [comment]
Thx @mivano
