### ISSUE TITLE
Federated credentials

### ISSUE THREAD

**Issue by svrooij** [mivano/azure-cost-cli#160]
Please, please, please stop showing login in with 'credentials' from the GitHub action.

Microsoft invested a lot in security, and federated credentials is one of those features that should be favored over using client secrets.

Check out the docs on [federated credentials in Measter](https://maester.dev/docs/monitoring/github#create-github-action-worklow-for-maester).

It allows you to login by trusting a certain GitHub workflow and keeps you from creating/managing the secret.

**Comment by mivano** [comment]
You are right, that needs to switch to OpenID connect. I will include this in the readme. Thanks

**Comment by mivano** [comment]
Readme updated.

**Comment by svrooij** [comment]
This looks like such a small change but is so good for security!
Keep up the great work you're doing with this cli!

**Comment by mivano** [comment]
Totally right, thanks!
