### ISSUE TITLE
Missing resources : 

### ISSUE THREAD

**Issue by stewartadvt** [mivano/azure-cost-cli#169]
Hi

I am querying with azure-cost costByResource  -o csv -s <redacted> >> 1.csv

And I am not getting all my resources returned. 

1/2 my log analytic workspaces have not been returned 

Is there a way to make sure i get all resources returned ~

Thanks

**Comment by stewartadvt** [comment]
It may be related to this 

https://stackoverflow.com/questions/74109255/azure-api-not-returning-all-resources

**Comment by mivano** [comment]
The latest version does support pagination, earlier version only fetched the first 5000 items. So make sure to use the latest version. You can also use `-debug` to see the calls being made, as that should show multiple pages being fetched.

**Comment by mivano** [comment]
I hope the issue was related to pagination and the latest version fixed that for you. If not, feel free to reopen.
