### ISSUE TITLE
Resource Group not being contained in the export when having dimension ResourceGroup

### ISSUE THREAD

**Issue by vanwinkelseppe** [mivano/azure-cost-cli#174]
Hi there,

We've made plenty of use if this tool but recently we upgraded to the latest version (0.37.0 -> 0.41.0)

We've noticed that the:
`azure-cost dailyCosts --dimension ResourceGroup -t custom --from 09/01/2024 --to 10/01/2024 --includeTags -o csv`

Returns a different layout then before. For example it doesn't include the dimension you are filtering on anymore ^

Example before:
`
Date,Name,Cost,CostUsd,Currency,Tags
8/1/2024,,0.00979290,0.01059200,EUR,
8/1/2024,$system,0.29824704,0.32258400,EUR,
8/1/2024,rg-cosmos-we,2.75148580,2.97600704,EUR,costcenter:shared;costsubcenter:cosmos table storage;environment:test
`

Example now:
`
Date,Cost,Currency,CostUsd,costcenter,costsubcenter,environment
9/1/2024,0.21563342,EUR,0.24000000,shared,networking,developmentsandbox
`

We still use the same command, is there a way to reinclude the dimension you are actually querying?

**Comment by mivano** [comment]
That does not look correct. I traced it back to the change that includes the tags. Apparently, I forgot the mapping of the `name` property. Version 0.41.0 should have the field again. Sorry for the trouble.

**Comment by vanwinkelseppe** [comment]
Great thanks for the fix!
