### ISSUE TITLE
From parameter ignored

### ISSUE THREAD

**Issue by martijnhoogendoorn** [mivano/azure-cost-cli#27]
When specifying a --from, it seems to ignore the input, taking the current date, where the --to parameter seems to be properly propagated to the API. --debug shows this:

_azure-cost --debug -s c345e773-72a5-4731-4ab6-8f371e38f7e6 --from 2023-04-01 --to 2023-04-30_

Retrieving data from /subscriptions/c04fee73-7da3-4835-8ae1-6f373ee81794/providers/Microsoft.CostManagement/forecast?api-version=2021-10-01&$top=5000 using the following payload:
{
   "type": "ActualCost",
   "timeframe": "Custom",
   "timePeriod": {
      **"from": "2023-05-02",**
      "to": "2023-04-30"
   },

**Comment by mivano** [comment]
I believe this is related to #28. For the forecast, it takes the last retrieved date from the actual cost and takes it from there. So in that sense _by design_, but I might need to rethink that design.
