### ISSUE TITLE
Forecast causing crash on custom timeframe

### ISSUE THREAD

**Issue by martijnhoogendoorn** [mivano/azure-cost-cli#28]
When specifying historical timeframe to get the cost, because the forecast is always executed in code, it fails with no proper output. Example:

azure-cost accumulatedCost --debug -s XXXX -t Custom --from 2023-01-01 --to 2023-04-30 -o json

yields

Response status code is BadRequest and got payload size of 76
Response content: {"error":{"code":"CantForecastOnThePast","message":"CantForecastOnThePast"}}

because the forecast API is passed the from/to dates.

**Comment by mivano** [comment]
I fixed a couple of things in v0.14.0 that should address this.

**Comment by mivano** [comment]
Closing this one as fixed. If not, feel free to reopen.
