### ISSUE TITLE
unable to install "dotnet tool install --global azure-cost-cli". 

### ISSUE THREAD

**Issue by soumyojit28** [mivano/azure-cost-cli#31]
dotnet sdk version 6.0.408

error: 
 error NU1100: Unable to r
esolve 'azure-cost-cli (>= 0.0.0)' for 'net6.0/any'.
The tool package could not be restored.
Tool 'azure-cost-cli' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by mivano** [comment]
I m unsure how to help with this, as it is the dotnet tool that reports this issue. I assume you followed the install instructions here: https://www.nuget.org/packages/azure-cost-cli ?

**Comment by soumyojit28** [comment]
still the issue is persist, as I am using with global and local

**Comment by mivano** [comment]
You do have the .net 6 or .net 7 runtime installed?

**Comment by soumyojit28** [comment]
I have tried from both but same error coming.

**Comment by mivano** [comment]
I do not think it has anything to do with this specific tool as it is not yet installed. Try to install another dotnet tool to rule out that your package sources and connection are working fine.

Might be something similar to https://github.com/dotnet/sdk/issues/11325

**Comment by mivano** [comment]
Closing this one as I do not know how to solve this and it looks like an issue with the dotnet tool installer.

**Comment by mivano** [comment]
What I noticed, is that most of the time this is due to a nuget configuration that is set incorrectly. You might have a corporate nuget feed added as well. 

You could try to add `--ignore-failed-sources` to the dotnet command to see if that works.

Or try something like this:

`dotnet tool update --global [tool] --add-source 'https://api.nuget.org/v3/index.json' --ignore-failed-sources`

**Comment by hannesbreit** [comment]
awesome! that worked just like a charm

**Comment by hannesbreit** [comment]
it was the add-source

**Comment by mivano** [comment]
Thanks, that forces the use of the specific nuget feed. If you execute `dotnet nuget list source` you might see others than the official api.nuget.org
