### ISSUE TITLE
400 (Bad Request) when attempting to use CostByResource 

### ISSUE THREAD

**Issue by ncardin** [mivano/azure-cost-cli#33]
Hi - I'm experiencing issues using the CostByResource parameter.

The ServiceTier does not appear to be valid. 
 
Version: 0.16.0

Command: azure-cost costByResource -s {SUBSCRIPTION_ID} --debug
 
Error: Error: Response status code does not indicate success: 400 (Bad Request).

Detailed Error: Response status code is BadRequest and got payload size of 903
Response content: {"error":{"code":"BadRequest","message":"Invalid query definition: Invalid dataset grouping:
'ServiceTier'; valid values:
'ResourceGroup','ResourceGroupName','ResourceType','ResourceId','ResourceLocation','SubscriptionId','SubscriptionName','
MeterCategory','MeterSubcategory','Meter','ServiceFamily','UnitOfMeasure','PartNumber','BillingAccountName','BillingProf
ileId','BillingProfileName','InvoiceSection','InvoiceSectionId','InvoiceSectionName','Product','ResourceGuid','ChargeTyp
e','ServiceName','ProductOrderId','ProductOrderName','PublisherType','ReservationId','ReservationName','Frequency','Invo
iceId','PricingModel','CostAllocationRuleName','MarkupRuleName','BillingMonth','Provider','BenefitId','BenefitName','Cus
tomerTenantId','CustomerTenantDomainName','ResellerMPNId','PartnerEarnedCreditApplied','CustomerName','PartnerName',''.\
r\n\r\n

**Comment by mivano** [comment]
I think I found the culprit. Some conversion (https://learn.microsoft.com/en-us/azure/cost-management-billing/automate/migrate-ea-usage-details-api#data-field-mapping) was needed. Could you please try 0.29.0 ?
