### ISSUE TITLE
[Bug] image not displayed

### ISSUE THREAD

**Issue by dtcMLOps** [mivano/azure-cost-cli#34]
Hi @mivano,

I hope you find well.

I have been testing this action and is working great. Do you know why I am getting an image rendering issue on the summary?

```bash
Unable to render rich display

Diagram error not found.

For more information, see https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams
```

![Screenshot from 2023-05-18 10-10-53](https://github.com/mivano/azure-cost-cli/assets/115469901/d7ac81f9-96c4-4c10-856c-b561e2f7cd97)

**Comment by dtcMLOps** [comment]
After testing this on mermaid.live, the problem seems to be the "," floating number in the chart

``m̀ermaid
pie title Cost by service
   "Virtual Machines" : 64,839.33
   "Azure Databricks" : 24,267.22
   "Storage" : 23,995.09
   "Azure Synapse Analytics" : 23,315.71
```

**Comment by mivano** [comment]
Thanks for reporting and spotting the issue. I changed the formatter used there so it outputs a value without the "," 
Update to the 0.17.0 release for this fix.

**Comment by mivano** [comment]
I m assuming this fixed the issue for you. If not, feel free to reopen the issue.

**Comment by dtcMLOps** [comment]
Hi @mivano,

Thanks for a such quick response. Indeed the above issue was solved, but there is still one image that is not rendered

## By Resource Group

```mermaid
pie
   title Cost by resource group
   "" : 10686.30
   "global-a" : 8564.11
   "mgmt" : 4565.96
   "Others" : 156801.56
```

It seems there is one resource with an empty name

**Comment by mivano** [comment]
Ah that is another nice edge case. Is fixed in v0.18.0

**Comment by dtcMLOps** [comment]
Hi @mivano, this has been solved.  All the images are now rendered. The only thing is that the resource group that has a name with a dash "-" is now called "unknown", but that is ok since is not the resource group of my interest.

![Screenshot from 2023-05-22 06-02-03](https://github.com/mivano/azure-cost-cli/assets/115469901/d3f5101c-0b9f-475a-8725-b51144bb3871)

**Comment by mivano** [comment]
Good to see it does render now, but still a bit strange. It is a check for `string.IsNullOrWhitespace`, which somehow maps to true here. There is some other explicit mapping happing before, maybe that is causing the issue.

Can you give me the full name of the resource group? At least the structure, if you want to obfuscate the name, that is fine. But something that I can create in my own testing subscription to see if I can reproduce it.

**Comment by dtcMLOps** [comment]
Hi @mivano, sure. The name is

![Screenshot from 2023-05-22 17-38-24](https://github.com/mivano/azure-cost-cli/assets/115469901/01eb6fe4-b903-4623-a392-31d11346801a)

This is the one that is missing from the chart and in the table as well
![Screenshot from 2023-05-22 17-39-19](https://github.com/mivano/azure-cost-cli/assets/115469901/8496b145-37f3-40d8-bd1d-2e25eecb7fcb)

**Comment by mivano** [comment]
I created a resource group with that name, but I do see it fine in the markdown. So I m still unsure why it does not happen with me as well. Not sure if you are able to, but if you can debug and see what `RetrieveCostForResources` function in the `AzureCostApiRetriever.cs` file does, then you might be able to find out why it does not parse it correctly. 

|-rg-global-non-prod|0,00 USD|

**Comment by dtcMLOps** [comment]
Hi @mivano I have tried

```bash
azure-cost -o json --query "ByResourceGroup[?ResourceGroup == '-rg-global-non-prod']"
```
and the response is:
```bash
[]
```
