### ISSUE TITLE
[question] change report currency

### ISSUE THREAD

**Issue by dtcMLOps** [mivano/azure-cost-cli#35]
Hi @mivano 

I was wondering if there is a filter or input parameter to define the report currency since I will need the report in USD instead EUR

**Comment by mivano** [comment]
This is a bit tricky; there is no explicit filter option on the cost API to specify a different currency, but you can request the cost in USD. This was already done, but not shown (and there was an incorrect mapping). 

So in version 0.17.0 you will get the cost, the currency (which can be EUR) and the CostUSD field in the JSON output formatter. 

Will this suffice?

**Comment by dtcMLOps** [comment]
This looks really good. Do you think this can be displayed in the markdown format as well?

**Comment by mivano** [comment]
It could, but I am wondering if it does not become confusing if there are two values displayed (a local currency and the USD version). For the JSON and CSV export it does not really matter, but the console, text, and markdown formatters are already overloaded with data.

What if I introduce a flag that forces the values to be outputted as USD instead? If false, it uses the values in the currency we get from the API; if true, it returns the USD version instead. Would that be okay for your use case, or are you looking for both values at the same time?

**Comment by dtcMLOps** [comment]
Hi @mivano,

actually this is the perfect approach. A flag that we can use to decide if we want the local currency or in USD sounds perfect

**Comment by mivano** [comment]
Implemented in version 0.19. Use the `--useUSD true` parameter to force the formatters to use the USD currency.

**Comment by dtcMLOps** [comment]
Hi @mivano this is working perfectly

![Screenshot from 2023-05-22 17-45-55](https://github.com/mivano/azure-cost-cli/assets/115469901/8b21b85b-139e-4718-9c74-93cc0ce93d49)
