### ISSUE TITLE
[question] how to get report by one resource group

### ISSUE THREAD

**Issue by dtcMLOps** [mivano/azure-cost-cli#36]
Hi @mivano 

Greetings.

How can I get the report for 1 resource group in the subscription? For example:

**resource group name**: my-new-resource-group

My command:

```bash
azure-cost -o json --query "[my-new-resource-group].[ResourceGroup, Cost]"
```

I don't understand how to use the query filter to get the data just for one resource group.

- Also, do you think this filter is just for the json output format or could be used with the markdown format too?
- Also, do you know if I can pass to the query filter a "tag" for getting only resources with a specific tag? 

The idea with this is to get the report for a specific project that belongs to a specific resource group in the subscription.

**Comment by mivano** [comment]
The [jmespath](https://jmespath.org) will only work for the json formatter, unfortunately. 

Selecting a single resource group:

`-o json --query "ByResourceGroup[?ResourceGroup == 'my-new-resource-group']"`

Or to only get the specific fields:

`-o json --query "ByResourceGroup[?ResourceGroup == 'my-new-resource-group'].[ResourceGroup, Cost]"`

I still intend to add an additional filter parameter which is mapped to the API calls, but there are a lot of options, so I need to find the right way to do so. Then it will just retrieve what you want from the cost API. The query option filters on all the data it already retrieved. 

So to answer your second question; no, not yet using the query option. With an explicit filter, that might be possible.

Track it here #20

**Comment by dtcMLOps** [comment]
Hi @mivano, the above is working great. Thanks!

**Comment by mivano** [comment]
Excellent!
