### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by MarianDanisek** [mivano/azure-cost-cli#40]
I have tried install solution but i'm getting this error :

PS C:\Users\marian.danisek> dotnet tool install --global azure-cost-cli
C:\Users\marian.danisek\AppData\Local\Temp\d376cbd6-6106-416d-b0d5-2964222e471e\restore.csproj : error NU1100: Unable t
o resolve 'azure-cost-cli (>= 0.0.0)' for 'net7.0'.
C:\Users\marian.danisek\AppData\Local\Temp\d376cbd6-6106-416d-b0d5-2964222e471e\restore.csproj : error NU1100: Unable t
o resolve 'azure-cost-cli (>= 0.0.0)' for 'net7.0/any'.
The tool package could not be restored.
Tool 'azure-cost-cli' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by mivano** [comment]
There might be a couple of issues here:
1. Check if you have the .net 6 or 7 runtime installed.
2. Check if you are using the right nuget source. You might have another one configured, a proxy in between etc. Try to install another dotnet tool, to see if it works. See #31

**Comment by MarianDanisek** [comment]
This solved issue:
1. Clearing the NuGet cache using dotnet nuget locals all --clear
2. Deleting the NuGet.config file present inside C:\Users\<username>\AppData\Roaming\NuGet

**Comment by mivano** [comment]
Good to see it is fixed and thanks for the feedback!

**Comment by code2exe** [comment]
> This solved issue:
> 
> 1. Clearing the NuGet cache using dotnet nuget locals all --clear
> 2. Deleting the NuGet.config file present inside C:\Users<username>\AppData\Roaming\NuGet

This resolved my issue as well.

Thank you for the insight!
