### ISSUE TITLE
[feature request] filter results by 1 resource group including tags

### ISSUE THREAD

**Issue by dtcMLOps** [mivano/azure-cost-cli#43]
Hi @mivano 

Greetings.

I was wondering if there will be a future development for filtering out results with a "tag" for 1 specific resource group. This will be a real improvement in getting the costs per project.

Related to #20

**Comment by mivano** [comment]
I agree, I would like to add this feature. The calls to the cost API endpoint support filters, but I need to find a way to build up those filters from command line arguments. 

In your use case, what is the expected result? What kind of filter do you want to pass along, and what should it return? Can you provide a more concrete sample?

**Comment by dtcMLOps** [comment]
Hi @mivano, so the idea is that I can pass a **tag** to the app so we can get all the same information in the markdown/json format, but just for 1 resource group. (This is the same as we can do in the UI)

![Screenshot from 2023-06-09 08-58-52](https://github.com/mivano/azure-cost-cli/assets/115469901/297031a4-3321-4385-9123-22f181f70dbf)

For example, I found this GA with a similar initiative: https://github.com/marketplace/actions/azure-cost-report-action where there is a parameter called `includeTags` to filter out results:

```bash
includeTags: "team,owner"
```

I have tested that action, but it seems is not working.

So, the ideal output I think would be to have something like this (accumulated cost, by service, by country, etc)

![image](https://github.com/mivano/azure-cost-cli/assets/115469901/05cd5870-ac3e-4cd1-a0dd-2321d1f0b361)

but scope to 1 resource group and a tag parameter. The output in markdown format would be great, but the output in json format would be better for sending alerts and messages in our communication channel about costs results

**Comment by mivano** [comment]
I m working on a solution. Not ready yet, I need to test the edge cases, but have a look at the (small) documentation here to see if that is what can work for you: https://github.com/mivano/azure-cost-cli/tree/filtering#filter

Remember; not yet available, still on a branch.

**Comment by mivano** [comment]
Merged now, version 0.23.0 contains the filter option. See the readme for an example. 

Please let me know if this suits your use case.

**Comment by dtcMLOps** [comment]
Hi @mivano this is working as expected, thank you so much.
