### ISSUE TITLE
Unable to use the --from --to option when --timeframe is set to Custom

### ISSUE THREAD

**Issue by matthieupetite** [mivano/azure-cost-cli#46]
Hello, 

As displayed in the picture bellow I dont understand how to specify the from and to parameter when the timefarame is set to custom. Can you please provide a sample in the readme if possible. 

![image](https://github.com/mivano/azure-cost-cli/assets/4076681/979957f6-7b31-40e0-9d55-d9171f626538)

Thanks a lot in advance

Regards

**Comment by mivano** [comment]
I added typeconvertors for net6. Hard for me to validate if that solves the issue, but at least this is covered in this issue now.
