### ISSUE TITLE
Deserialization issue when calling dailyCost and output to Json

### ISSUE THREAD

**Issue by matthieupetite** [mivano/azure-cost-cli#47]
It seems that there is a bug when exporting the cost in json because of the Serialization and deserialization of the System.DateOnly attributes 

here are the command line executed 

![image](https://github.com/mivano/azure-cost-cli/assets/4076681/ff4bdb01-d555-4f7b-ac09-1a842e07f392)

**Comment by matthieupetite** [comment]
In order to fix that issue I just use the dotnet 7 version fo the sdk

**Comment by mivano** [comment]
Thanks for reporting. It looks like it is indeed not supported in net6. I added a fix for this.
