### ISSUE TITLE
Latest installer shows wrong CLI command

### ISSUE THREAD

**Issue by martijnvanschie** [mivano/azure-cost-cli#5]
Just ran the installer and the --help show the wrong CLI command.

It shows 'Azure Cost [OPTIONS]' instead of 'azure-cost [OPTIONS]'

![image](https://user-images.githubusercontent.com/8370550/232097564-6e27327c-6fcc-4441-a3ed-7d3b1848877a.png)

**Comment by mivano** [comment]
Check, fixed in https://github.com/mivano/azure-cost-cli/pull/2 

Thanks for reporting!
