### ISSUE TITLE
Question. Can I iterate all subscriptions on a tenant with azure-cost-cli and get a CSV with their consumption?

### ISSUE THREAD

**Issue by farreciado** [mivano/azure-cost-cli#55]
That's all. Take advantage of the tool to loop my subscriptions and get a single report for all of them.

**Comment by mivano** [comment]
Have a look at this: https://github.com/mivano/azure-cost-cli/discussions/41

does this solve your question?

**Comment by farreciado** [comment]
That's exactly the loop I was searching for...only a point to solve. I modified it to get the AccumulatedCosts , and got a nice CSV, but the CSV file does not includes the suscription ID or name, so I cannot differentiate rows.

For each one, I have one line per day, such this:

Date,Cost,CostUsd,Currency
5/1/2023,0.79816372434144,0.864491129834212,EUR
5/2/2023,0.79816332016544,0.864490692071186,EUR
5/3/2023,0.79816355536544,0.864490946816306,EUR

How can I extend the output to include suscription info?

**Comment by mivano** [comment]
As you know for what subscription you call the tool, you can either output the data to a {subscriptionid}.csv and then process it further. 

alternatively, parse the payload (json or csv) in powershell/bash and output a new structure to your liking. 

another option is to use the costByResource command. This one has the resourceid which contains the subscription id, resourcegroup and resource name.

**Comment by mivano** [comment]
There is some nasty rate limiting. It should however handle that, but I did notice that sometimes I get a different header with a retry after value. I will have a look at that.

**Comment by mivano** [comment]
Version 0.28 contains some better retry logic. Hope that helps.

**Comment by farreciado** [comment]
Thanks! I got today's version and shows much more info, while stills showing some error codes:
Error: Response status code does not indicate success: 404 (Not Found).
Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

**Comment by mivano** [comment]
Thanks, some more work to do I see with the policy. I can fine-tune the timeout, but the 404 is strange.

**Comment by mivano** [comment]
I added some additional handling in 0.28. Hope that helps
