### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by PetreHoffmann** [mivano/azure-cost-cli#59]
azure-cost accumulatedCost -s id returns

Error: Response status code does not indicate success: 401 (Unauthorized).

running az login before azure-cost return same result.
How can I login in azure-cost cli?

**Comment by mivano** [comment]
This sometimes happens when your subscription is in another tenant. Use the `az login --tenant nameorid` to force it to login for that specific tenant. You might need to do a 2FA challenge for example.

**Comment by PetreHoffmann** [comment]
Thank you @mivano
