### ISSUE TITLE
Savings analysis DevTest/Savings plan/Reservations

### ISSUE THREAD

**Issue by aristosvo** [mivano/azure-cost-cli#61]
Hi @mivano! Thanks for building this nice tool.

What we see currently is that it is very hard to do a quick analysis what DevTest subscriptions would save us.

It would be nice to have functionality to do some of the cost calculations upfront with `azure-cost`!

**Comment by mivano** [comment]
Interesting idea; so scan a subscription, fetch the current cost, and determine what you would save when it was a DevTest subscription?

**Comment by aristosvo** [comment]
Exactly that :) 

I've tried it with some `jq` logic, but it seems SKUs between the retail price API and output of `azure-cost` was not a 1-to-1 atm, using i.e. this: `https://prices.azure.com/api/retail/prices?currencyCode='EUR'&$filter=priceType eq 'DevTestConsumption' and Location eq 'EU West' and serviceName eq 'Azure App Service'`

**Comment by mivano** [comment]
I was already working (in a feature branch) on functionality to fetch the marketplace prices. I think this is a great use case: optimizing money by using a different subscription type. Thanks for the suggestion!

**Comment by aristosvo** [comment]
Awesome! Happy to help with testing btw.

We've calculated the savings for a few of our subscriptions now by hand/Excel, we can easily compare the results there!

**Comment by mivano** [comment]
I will be on holiday for a couple of weeks, so do not expect it soon. Will update the issue when I have something to try out.
