### ISSUE TITLE
Cost by Tag

### ISSUE THREAD

**Issue by dellycowboy** [mivano/azure-cost-cli#64]
We use tags extensively to breakdown business ownership and recharge back to them.

Would it be possible to add byTag and then for it to take 1 or more tags. The breakdown csv/putput should then have a column for each tag specified.

**Comment by mivano** [comment]
Interesting idea. Let me see what I can come up with.

**Comment by mivano** [comment]
Please have a look at version 0.32 which contains the `costByTag` command and let me know if this suits your needs.
